### ISSUE TITLE
Load Vue components in markdown  - component not found

### ISSUE THREAD

**Issue by qu1ckdry** [hmsk/frontmatter-markdown-loader-nuxt-sample#5]
Hi!

I'm trying to create a nuxt blog with your markdown loader. I've gone through both this and your your 'frontmatter-markdown-loader' repo. My goal is to add vue components to the markdown file which will then be loaded dynamically based on the route.

I've got this repo up and running locally but when I visit 'http://localhost:3000/article?name=quruli' via the 'quruli.md' link on the home page the <link-to-wikipedia> component doesn't load. The error in the console reads:

> Unknown custom element: <link-to-wikipedia> - did you register the component correctly?

Is this the expected behavior? Should I switch to the vue.render approach?

Thanks for your help!

**Comment by hmsk** [comment]
Thanks for pointing this out. At some point, `<link-to-wikipedia>` component isn't hooked by Nuxt automatically, and I didn't notice 😇 Just fixed on this commit https://github.com/hmsk/frontmatter-markdown-loader-nuxt-sample/commit/9766bb75c7fac533a1c48ffd61200adb45a5784b, so pull the latest and try!

**Comment by qu1ckdry** [comment]
Thanks for the quick response @hmsk. The fix works great in both your example and my implementation!
